### PR TITLE
Add common directory

### PR DESCRIPTION
**Pull request by remimimimimi**
## Description of changes

Add directory that allow user to share files between appvms and guivm easily.

## Checklist for things done

- [x] Summary of the proposed changes in the PR description
- [ ] More detailed description in the commit message(s)
- [x] Commits are squashed into relevant entities - avoid a lot of minimal dev time commits in the PR
- [x] [Contribution guidelines](https://github.com/tiiuae/ghaf/blob/main/CONTRIBUTING.md) followed
- [ ] Ghaf documentation updated with the commit - https://tiiuae.github.io/ghaf/
- [ ] PR linked to architecture documentation and requirement(s) (ticket id)
- [x] Test procedure described (or includes tests). Select one or more:
  - [x] Tested on Lenovo X1 `x86_64`
  - [ ] Tested on Jetson Orin NX or AGX `aarch64`
  - [ ] Tested on Polarfire `riscv64`
- [ ] Author has run `make-checks` and it passes
- [ ] All automatic Github Action checks pass - see [actions](https://github.com/tiiuae/ghaf/actions)
- [ ] Author has added reviewers and removed PR draft status
- [x] Change requires full re-installation
- [ ] Change can be updated with `nixos-rebuild ... switch`

## Instructions for Testing

- [x] List all targets that this applies to: every target.
- [x] Is this a new feature
  - [x] List the test steps to verify:
    1. Connect to chromium-vm and create file in `/home/ghaf/Unsafe share` directory.
    2. Go back to guivm and move file from `/home/ghaf/Shares/Unsafe chromium-vm share` to `/home/ghaf/Shares/Unsafe business-vm share`.
    3. Connect to business vm and check that file appears in `/home/ghaf/Unsafe share` directory.
    4. Check that file stays in place after reboot.
- [ ] If it is an improvement how does it impact existing functionality?

### CODE REVIEW

**Comment by milva-unikie** [comment]
**Tested on Lenovo-X1** (`nixos-rebuild switch`)

(PR checklist asks for a full re-installation, but this also works fine with `nixos-rebuild switch`. Checked with @remimimimimi that it is ok to use.)

I know this pr is not supposed to be the perfect solution, but I think it is not enough for User trial users as is. The biggest issues I see are the need to use the command line and no support for Slack (comms-vm).

From a technical point of view this works well. I am however looking at this mostly from the perspective of our users. 

Working:
- The steps in Testing instructions work. From Chromium you can select an image, click "Save image as..." and select to save it to "Unsafe share". Then in gui-vm from command line you can `cp` the image from "Unsafe chromium-vm share" to "Unsafe business-vm share". And finally in Outlook you can select Insert -> Attach file -> Browse this computer -> Unsafe share -> select file.
- Files in "Unsafe share" are saved between boots.

Issues:
- This requires the user to use command line to move the files around.
- Only chromium-vm and business-vm are supported. I would think at least comms-vm should also be included?
- There is not always an option to select where to save a file. For example pdf files are automatically downloaded to the Downloads-folder. The user can ssh to chromium and copy the file from Downloads to "Unsafe share", but that again requires the user to use command line.
- Also, could we get folder names with no spaces in them please? It does not look pretty atm `cp Unsafe\ chromium-vm\ share/sample.pdf Unsafe\ business-vm\ share/`

**Comment by milva-unikie** [comment]
Tested this pr together with https://github.com/tiiuae/ghaf/pull/804 that will add a file manager to Ghaf.

With the file manager user can copy files around in gui-vm easily (as long as the file is not too big because then the system will freeze. That is a separate bug that is already known.)

> This requires the user to use command line to move the files around.

So that one issues is resolved for gui-vm. I believe all of the others are still valid.

**Comment by remimimimimi** [comment]
Added unsafe share directory for comms-vm and configured chromium to ask user where to save file on every download.

**Comment by milva-unikie** [comment]
**Tested on Lenovo-X1** (full re-installation)

Working:
- User can select to save a file to the Unsafe share 
  - Chromium now always prompts the user to select the location where to save a file -> Unsafe share can be selected
- (This pr is not yet rebased, but https://github.com/tiiuae/ghaf/pull/804 makes it possible to move the file between different shares in gui-vm using gui).
- The Unsafe share is supported in chromium-vm, comms-vm and business-vm.
- Files in "Unsafe share" are saved between boots.

**Review by brianmcgillion — APPROVED** [review]

**Pull request merged**
