### PR TITLE
Taskbar replacement using EWW

### PR DESCRIPTION
**Pull request by kajusnau**
## Description of changes

Proposed waybar taskbar replacement using [Elkowars Wacky Widgets](https://github.com/elkowar/eww), with modified base config made by https://github.com/rxyhn.
Main taskbar configuration is defined in `modules/desktop/graphics/ewwbar.nix` and stored in `/etc/eww/eww.yuck`.
Styling defined in `modules/desktop/graphics/ewwbar.nix` and stored in `/etc/eww/eww.css`.
Available widgets (from left to right):
- Launcher;
- Battery;
- Wifi;
- Bluetooth (currently disabled);
- Security (currently disabled);
- Keyboard layout indicator;
- Clock;
- Date;
- Calendar (can be opened through date widget).

Known issues:
- Currently, it is only possible to read the initial keyboard layout set during boot (US, as defined in `modules/desktop/profiles/graphics.nix`). Any subsequent changes made to the keyboard layout are not reflected (ref. https://github.com/labwc/labwc/issues/1705);
- Bar currently reserves bottom ~5% of the available screen real estate.
Design can be adjusted to hide bar automatically, move it to the top, or similar. TBD
- All icons (https://github.com/tiiuae/ghafpkgs/pull/6) are fixed size 24x24, sizes should be scalable instead;
- No power widgets
- No bluetooth widget
- Bar is duplicated automatically for additional displays **only during system boot**;

## Checklist for things done

- [x] Summary of the proposed changes in the PR description
- [x] More detailed description in the commit message(s)
- [x] Commits are squashed into relevant entities - avoid a lot of minimal dev time commits in the PR
- [x] [Contribution guidelines](https://github.com/tiiuae/ghaf/blob/main/CONTRIBUTING.md) followed
- [ ] Ghaf documentation updated with the commit - https://tiiuae.github.io/ghaf/
- [ ] PR linked to architecture documentation and requirement(s) (ticket id)
- [x] Test procedure described (or includes tests). Select one or more:
  - [x] Tested on Lenovo X1 `x86_64`
  - [ ] Tested on Jetson Orin NX or AGX `aarch64`
  - [ ] Tested on Polarfire `riscv64`
- [ ] Author has run `make-checks` and it passes
- [x] All automatic Github Action checks pass - see [actions](https://github.com/tiiuae/ghaf/actions)
- [x] Author has added reviewers and removed PR draft status
- [ ] Change requires full re-installation
- [x] Change can be updated with `nixos-rebuild ... switch`

## Instructions for Testing
Can be tested on VM or Lenovo X1 following usual installation
Note: New icons are not yet in latest ghafpkgs mainline, therefore this PR should be used: https://github.com/tiiuae/ghafpkgs/pull/6
Flake should be adjusted accordingly:
**flake.nix**:
```
...
ghafpkgs = {
      url = "github:tiiuae/ghafpkgs/new-icons";
...
```
- [ ] List all targets that this applies to:
- [x] Is this a new feature
  - [x] List the test steps to verify:
  Mentioned above
- [ ] If it is an improvement how does it impact existing functionality?

### CODE REVIEW

**Comment by leivos-unikie** [comment]
Tested on Lenovo-X1 (via nixos-rebuild switch)
- All Menu icons work
- ci-test-automation passes (except boot time measurement which was just merged and searches the old waybar logs)
- performance ok
- Apart from the known issues, the only drawback I found is that the ewwbar is not shown on external display. It makes working with extended display a bit annoying when app menu can accessed only from laptop display. With waybar the bar was shown also on external display.

**Comment by juliuskoskela** [comment]
> Tested on Lenovo-X1 (via nixos-rebuild switch)
> 
>     * All Menu icons work
> 
>     * ci-test-automation passes (except boot time measurement which was just merged and searches the old waybar logs)
> 
>     * performance ok
> 
>     * Apart from the known issues, the only drawback I found is that the ewwbar is not shown on external display. It makes working with extended display a bit annoying when app menu can accessed only from laptop display. With waybar the bar was shown also on external display.

Good catch with the external monitor support. We'll try to find a solution to mirror the UI to all connected displays so as not to get a regression from previous Waybar setup.

**Comment by juliuskoskela** [comment]
Tested in a a Virtual Machine.

## Bugs

- Network-button (wifi-icon) doesn't open nmcli or other networking settings when tested in a VM.

### Launcher

- Launcher appears glued to the bar. Should introduce spacing between bar and launcher. I suggest same spacing as between bar and bottom.
- Maybe launcher should have a X button in top right corner for closing. Some people might not intuitively re-click the launch icon.

### Bar

- Networking-button should have a "not-connected" state, grey with a red line.
- Networking-button should have a state for ethernet connection.

**Comment by leivos-unikie** [comment]
>     * Networking-button should have a state for ethernet connection.

Currently there is only debug eth connection to ghaf-host on X1. Are there some plans to change this? Eth connection pass through to net-vm?

**Comment by juliuskoskela** [comment]
Ok I tested with SSD-boot now and nm-launcher works from the wifi-icon. Running Ghaf in a VM, nm-launcher is broken as well as ssh connection to vm's inside Ghaf.

**Review by juliuskoskela — APPROVED** [review]

**Comment by kajusnau** [comment]
### Updated:
- ewwbar should now appear on all displays during boot;
- ewwbar will not adjust to additional displays during runtime, requires service restart or system reboot;
- calendar widget will open on the display where parent ewwbar resides
- ghaf-launcher is now spaced from the ewwbar same distance as calendar widget

**Comment by juliuskoskela** [comment]
Tested dual display setup.

image

Seems to work as expected with display connected via HDMI.

**Review by leivos-unikie — APPROVED** [review]
- If external display is disconnected and reconnected run-time the bar disappears from the external display (this was a known issue if I understood correctly)
- No critical issues found

**Comment by leivos-unikie** [comment]
Please go through / update the PR template checklist.

**Comment by kajusnau** [comment]
PR updated with updated flake lock for **ghafpkgs**

**Comment by milva-unikie** [comment]
I also tried this after the newest changes and everything seems to be working well!

**Pull request merged**
