### PR TITLE
License: make two files Apache-2.0, CC-BY-SA-4.0

### PR DESCRIPTION
**Pull request by jenninikko**
Now instead of one LICENSE file with Apache-2.0 we have two different files, as documentation goes under CC-BY-SA-4.0.

Also, added SPDX headers to all doc files, updated README.md.

Signed-off-by: Jenni Nikolaenko <evgeniia.nikolaenko@unikie.com>

### CODE REVIEW

**Comment by jenninikko** [comment]
Hello! @brianmcgillion, @vilvo 
Please check if I understood everything correctly and if we use the described licensing policy.

**Comment by mikatammi** [comment]
Just FYI, there is ongoing work to add SPDX License headers to all .nix files as well:
https://github.com/tiiuae/ghaf/commit/177a0979ce7c15f00d614b52d04c232a2699dea4

**Comment by jenninikko** [comment]
Thanks for the comment @mikatammi ^_^

I had a chat with Brian. We decided to use for the documentation:

```
<!--
    Copyright 2022-2023 TII (SSRC) and the Ghaf contributors
    SPDX-License-Identifier: CC-BY-SA-4.0
-->
```

I am going to update my pull request now.

**Review by vilvo — APPROVED** [review]
Looks good to me. @henrirosten is checking sbomnix SPDX (LF) support. Now it only supports CycloneDX (OWASP).

**Pull request merged**
