### PR TITLE
Update jetpack-nixos in flake.lock

### PR DESCRIPTION
**Pull request by mikatammi**
* Refactor flash script to use newly exposed mkFlashScript

### CODE REVIEW

**Comment by vilvo** [comment]
Failed on x86 more vocally:
```
ghaf (8ef1839) [$?] took 3s
❯ sudo nix run .#packages.x86_64-linux.nvidia-jetson-orin-debug-flash-script
[sudo] password for vilvo:

###############################################################################
# L4T BSP Information:
# R35 , REVISION: 3.1
###############################################################################
# Target Board Information:
# Name: jetson-agx-orin-devkit, Board Family: t186ref, SoC: Tegra 234,
# OpMode: production, Boot Authentication: NS,
# Disk encryption: disabled ,
###############################################################################
copying emc_fuse_dev_params(/tmp/tmp.9o4fSWn4e7/bootloader/t186ref/BCT/tegra234-br-bct-diag-boot.dts)... done.
copying device_config(/tmp/tmp.9o4fSWn4e7/bootloader/t186ref/BCT/tegra234-mb1-bct-device-p3701-0000.dts)... done.
copying misc_config(/tmp/tmp.9o4fSWn4e7/bootloader/t186ref/BCT/tegra234-mb1-bct-misc-p3701-0000.dts)... done.
./tegraflash.py --chip 0x23 --applet "/tmp/tmp.9o4fSWn4e7/bootloader/mb1_t234_prod.bin" --skipuid --cfg readinfo_t234_min_prod.xml --dev_params tegra234-br-bct-diag-boot.dts --device_config tegra234-mb1-bct-device-p3701-0000.dts --misc_config tegra234-mb1-bct-misc-p3701-0000.dts --bins "mb2_applet applet_t234.bin" --cmd "dump eeprom cvm cvm.bin; dump custinfo custinfo_out.bin; reboot recovery"
Welcome to Tegra Flash
version 1.0.0
Type ? or help for help and q or quit to exit
Use ! to execute system commands

[   0.0204 ] tegrarcm_v2 --chip 0x23 0 --ismb2applet
[   0.0206 ] File rcm_state open failed
[   0.0210 ] ERROR: failed to read rcm_state
[   0.0210 ]
[   0.0272 ] tegrasign_v3.py --key None --getmode mode.txt
[   0.0273 ] Assuming zero filled SBK key
[   0.0212 ] Pre-processing config: tegra234-mb1-bct-device-p3701-0000.dts
[   0.0320 ] Pre-processing config: tegra234-mb1-bct-misc-p3701-0000.dts
[   0.0431 ] Parsing partition layout
[   0.0434 ] tegraparser_v2 --pt readinfo_t234_min_prod.xml.tmp
[   0.0441 ] Kernel DTB used: None
[   0.0441 ] WARNING: dce base dtb is not provided

[   0.0441 ] Parsing partition layout
[   0.0444 ] tegraparser_v2 --pt readinfo_t234_min_prod.xml.tmp
[   0.0448 ] Creating list of images to be signed
[   0.0450 ] tegrahost_v2 --chip 0x23 0 --partitionlayout readinfo_t234_min_prod.xml.bin --list images_list.xml zerosbk
[   0.0452 ] MB1: Nvheader already present is mb1_t234_prod_aligned.bin
[   0.0458 ] Header already present for mb1_t234_prod_aligned_sigheader.bin
[   0.0460 ] MB1: Nvheader already present is mb1_t234_prod_aligned.bin
[   0.0495 ] Header already present for mb1_t234_prod_aligned_sigheader.bin
[   0.0497 ] MB1: Nvheader already present is psc_bl1_t234_prod_aligned.bin
[   0.0531 ] Header already present for psc_bl1_t234_prod_aligned_sigheader.bin
[   0.0533 ] adding BCH for mb2_t234_aligned.bin
[   0.0552 ] MB1: Nvheader already present is psc_bl1_t234_prod_aligned.bin
[   0.0651 ] Header already present for psc_bl1_t234_prod_aligned_sigheader.bin
[   0.0652 ] adding BCH for mb2_t234_aligned.bin
[   0.0769 ] Filling MB1 storage info
[   0.0769 ] Parsing dev params for multi chains
[   0.0870 ] Generating br-bct
[   0.0872 ] Updating dev and MSS params in BR BCT
[   0.0872 ] tegrabct_v2 --dev_param tegra234-br-bct-diag-boot_cpp.dtb --brbct br_bct.cfg --chip 0x23 0
[   0.0877 ] Updating bl info
[   0.0879 ] tegrabct_v2 --brbct br_bct_BR.bct --chip 0x23 0 --updateblinfo readinfo_t234_min_prod.xml.bin
[   0.0881 ] WARNING: boot chain is not completed. set to 0
[   0.0886 ] Generating signatures
[   0.0948 ] tegrasign_v3.py --key None --list images_list.xml --pubkeyhash pub_key.key --sha sha512
[   0.0948 ] Assuming zero filled SBK key
[   0.0987 ] Warning: pub_key.key is not found
[   0.0926 ] Parsing dev params for multi chains
[   0.0927 ] Generating br-bct
[   0.0929 ] Updating dev and MSS params in BR BCT
[   0.0929 ] tegrabct_v2 --dev_param tegra234-br-bct-diag-boot_cpp.dtb --brbct br_bct.cfg --chip 0x23 0
[   0.0932 ] Updating bl info
[   0.0934 ] tegrabct_v2 --brbct br_bct_BR.bct --chip 0x23 0 --updateblinfo readinfo_t234_min_prod.xml.bin --updatesig images_list_signed.xml
[   0.0936 ] WARNING: boot chain is not completed. set to 0
[   0.0941 ] Get Signed section of bct
[   0.0943 ] tegrabct_v2 --brbct br_bct_BR.bct --chip 0x23 0 --listbct bct_list.xml
[   0.0947 ] Signing BCT
[   0.1009 ] tegrasign_v3.py --key None --list bct_list.xml --pubkeyhash pub_key.key --sha sha512
[   0.1009 ] Assuming zero filled SBK key
[   0.1019 ] Sha saved in br_bct_BR.sha
[   0.1021 ] Warning: pub_key.key is not found
[   0.0959 ] Updating BCT with signature
[   0.0961 ] tegrabct_v2 --brbct br_bct_BR.bct --chip 0x23 0 --updatesig bct_list_signed.xml
[   0.0963 ] Offset :4608 Len :3584
[   0.0966 ] Generating SHA2 Hash
[   0.1027 ] tegrasign_v3.py --key None --list bct_list.xml --sha sha512
[   0.1028 ] Assuming zero filled SBK key
[   0.1028 ] Assuming zero filled SBK key
[   0.1037 ] Sha saved in br_bct_BR.sha
[   0.0977 ] Updating BCT with SHA2 Hash
[   0.0979 ] tegrabct_v2 --brbct br_bct_BR.bct --chip 0x23 0 --updatesha bct_list_signed.xml
[   0.0981 ] Offset :4608 Len :3584
[   0.0983 ] Offset :68 Len :8124
[   0.0984 ] Generating coldboot mb1-bct
[   0.0986 ] tegrabct_v2 --chip 0x23 0 --mb1bct mb1_cold_boot_bct.cfg --misc tegra234-mb1-bct-misc-p3701-0000_cpp.dtb --device tegra234-mb1-bct-device-p3701-0000_cpp.dtb
[   0.0988 ] MB1-BCT version: 0.10
[   0.0989 ] ERROR: carveout /misc/carveout/aux_info@CARVEOUT_UNUSED5/ is not supported
[   0.0992 ] ERROR: carveout /misc/carveout/aux_info@CARVEOUT_UNUSED5/ is not supported
[   0.0993 ] ERROR: carveout /misc/carveout/aux_info@CARVEOUT_UNUSED5/ is not supported
[   0.0994 ] ERROR: carveout /misc/carveout/aux_info@CARVEOUT_MCE_COVERAGE/ is not supported
[   0.0996 ] ERROR: carveout /misc/carveout/aux_info@CARVEOUT_MCE_COVERAGE/ is not supported
[   0.0997 ] ERROR: carveout /misc/carveout/aux_info@CARVEOUT_MCE_COVERAGE/ is not supported
[   0.0998 ] ERROR: /misc/tsc_controls/tsc_locking_config is not supported
[   0.0999 ] ERROR: /misc/tsc_controls/tsc_locking_diff_configuration is not supported
[   0.0999 ] ERROR: /misc/tsc_controls/tsc_locking_ref_frequency_configuration is not supported
[   0.0999 ] ERROR: /misc/tsc_controls/tsc_locking_control is not supported
[   0.0999 ] ERROR: /misc/tsc_controls/tsc_locking_adjust_configuration is not supported
[   0.0999 ] ERROR: /misc/tsc_controls/tsc_locking_fast_adjust_configuration is not supported
[   0.0999 ] ERROR: /misc/tsc_controls/tsc_locking_adjust_delta_control is not supported
[   0.0999 ] ERROR: /misc/tsc_controls/tsc_capture_control_ptx is not supported
[   0.0999 ] ERROR: /misc/tsc_controls/tsc_capture_config_ptx is not supported
[   0.0999 ] ERROR: /misc/tsc_controls/tsc_stscrsr is not supported
[   0.0999 ] ERROR: /misc/tsc_controls/tsc_locking_adjust_num_control is not supported
[   0.0999 ]
[   0.0999 ] Parsing config file :tegra234-mb1-bct-device-p3701-0000_cpp.dtb
[   0.0999 ] Added Platform Config 9 data with size :- 100
[   0.0999 ]
[   0.0999 ] Updating mb1-bct with firmware information
[   0.1001 ] tegrabct_v2 --chip 0x23 0 --mb1bct mb1_cold_boot_bct_MB1.bct --updatefwinfo readinfo_t234_min_prod.xml.bin
[   0.1008 ] tegrahost_v2 --chip 0x23 0 --align mb1_cold_boot_bct_MB1_aligned.bct
[   0.1013 ] tegrahost_v2 --chip 0x23 0 --magicid MBCT --appendsigheader mb1_cold_boot_bct_MB1_aligned.bct zerosbk
[   0.1015 ] adding BCH for mb1_cold_boot_bct_MB1_aligned.bct
[   0.1082 ] tegrasign_v3.py --key None --list mb1_cold_boot_bct_MB1_aligned_sigheader.bct_list.xml --pubkeyhash pub_key.key --sha sha512
[   0.1083 ] Assuming zero filled SBK key
[   0.1091 ] Warning: pub_key.key is not found
[   0.1032 ] tegrahost_v2 --chip 0x23 0 --updatesigheader mb1_cold_boot_bct_MB1_aligned_sigheader.bct.encrypt mb1_cold_boot_bct_MB1_aligned_sigheader.bct.hash zerosbk
[   0.1038 ] Generating recovery mb1-bct
[   0.1040 ] tegrabct_v2 --chip 0x23 0 --mb1bct mb1_bct.cfg --misc tegra234-mb1-bct-misc-p3701-0000_cpp.dtb --device tegra234-mb1-bct-device-p3701-0000_cpp.dtb
[   0.1042 ] MB1-BCT version: 0.10
[   0.1044 ] ERROR: carveout /misc/carveout/aux_info@CARVEOUT_UNUSED5/ is not supported
[   0.1047 ] ERROR: carveout /misc/carveout/aux_info@CARVEOUT_UNUSED5/ is not supported
[   0.1049 ] ERROR: carveout /misc/carveout/aux_info@CARVEOUT_UNUSED5/ is not supported
[   0.1051 ] ERROR: carveout /misc/carveout/aux_info@CARVEOUT_MCE_COVERAGE/ is not supported
[   0.1052 ] ERROR: carveout /misc/carveout/aux_info@CARVEOUT_MCE_COVERAGE/ is not supported
[   0.1052 ] ERROR: carveout /misc/carveout/aux_info@CARVEOUT_MCE_COVERAGE/ is not supported
[   0.1052 ] ERROR: /misc/tsc_controls/tsc_locking_config is not supported
[   0.1053 ] ERROR: /misc/tsc_controls/tsc_locking_diff_configuration is not supported
[   0.1053 ] ERROR: /misc/tsc_controls/tsc_locking_ref_frequency_configuration is not supported
[   0.1053 ] ERROR: /misc/tsc_controls/tsc_locking_control is not supported
[   0.1053 ] ERROR: /misc/tsc_controls/tsc_locking_adjust_configuration is not supported
[   0.1053 ] ERROR: /misc/tsc_controls/tsc_locking_fast_adjust_configuration is not supported
[   0.1053 ] ERROR: /misc/tsc_controls/tsc_locking_adjust_delta_control is not supported
[   0.1053 ] ERROR: /misc/tsc_controls/tsc_capture_control_ptx is not supported
[   0.1053 ] ERROR: /misc/tsc_controls/tsc_capture_config_ptx is not supported
[   0.1053 ] ERROR: /misc/tsc_controls/tsc_stscrsr is not supported
[   0.1053 ] ERROR: /misc/tsc_controls/tsc_locking_adjust_num_control is not supported
[   0.1053 ]
[   0.1053 ] Parsing config file :tegra234-mb1-bct-device-p3701-0000_cpp.dtb
[   0.1053 ] Added Platform Config 9 data with size :- 100
[   0.1053 ]
[   0.1053 ] Updating mb1-bct with firmware information
[   0.1055 ] tegrabct_v2 --chip 0x23 0 --mb1bct mb1_bct_MB1.bct --recov --updatefwinfo readinfo_t234_min_prod.xml.bin
[   0.1062 ] tegrahost_v2 --chip 0x23 0 --align mb1_bct_MB1_aligned.bct
[   0.1066 ] tegrahost_v2 --chip 0x23 0 --magicid MBCT --appendsigheader mb1_bct_MB1_aligned.bct zerosbk
[   0.1068 ] adding BCH for mb1_bct_MB1_aligned.bct
[   0.1135 ] tegrasign_v3.py --key None --list mb1_bct_MB1_aligned_sigheader.bct_list.xml --pubkeyhash pub_key.key --sha sha512
[   0.1135 ] Assuming zero filled SBK key
[   0.1143 ] Warning: pub_key.key is not found
[   0.1084 ] tegrahost_v2 --chip 0x23 0 --updatesigheader mb1_bct_MB1_aligned_sigheader.bct.encrypt mb1_bct_MB1_aligned_sigheader.bct.hash zerosbk
[   0.1090 ] Error: Skip generating mem_bct because sdram_config is not defined
[   0.1090 ] Error: Skip generating mem_bct because sdram_config is not defined
[   0.1090 ] Copying signatures
[   0.1092 ] tegrahost_v2 --chip 0x23 0 --partitionlayout readinfo_t234_min_prod.xml.bin --updatesig images_list_signed.xml
[   0.1121 ] mb1_t234_prod_aligned_sigheader.bin.encrypt filename is from images_list
[   0.1122 ] psc_bl1_t234_prod_aligned_sigheader.bin.encrypt filename is from images_list
[   0.1122 ] Boot Rom communication
[   0.1125 ] tegrarcm_v2 --new_session --chip 0x23 0 --uid --download bct_br br_bct_BR.bct --download mb1 mb1_t234_prod_aligned_sigheader.bin.encrypt --download psc_bl1 psc_bl1_t234_prod_aligned_sigheader.bin.encrypt --download bct_mb1 mb1_bct_MB1_sigheader.bct.encrypt
[   0.1127 ] BR_CID: 0x80012344705DD7C50400000011018200
[   0.1364 ] Sending bct_br
[   0.1645 ] ERROR: might be timeout in USB write.
Error: Return value 3
Command tegrarcm_v2 --new_session --chip 0x23 0 --uid --download bct_br br_bct_BR.bct --download mb1 mb1_t234_prod_aligned_sigheader.bin.encrypt --download psc_bl1 psc_bl1_t234_prod_aligned_sigheader.bin.encrypt --download bct_mb1 mb1_bct_MB1_sigheader.bct.encrypt
Reading board information failed.
```

**Comment by vilvo** [comment]
Board re-reset to APX mode takes further:
```
...
[   7.3330 ] Erasing spi: 0 .........
```

**Comment by vilvo** [comment]
`*** The target t186ref has been flashed successfully. ***`

**Review by vilvo — APPROVED** [review]
Works with no regression on x86, still does not work on aarc64 M1.

**Review by emrahbillur — APPROVED** [review]
Sorry for it took some time. I was waiting for one other config with build.

**Pull request merged**
