### PR TITLE
Slack: make metadata persistent

### PR DESCRIPTION
**Pull request by unbel13ver**
## Description of changes

This PR makes Slack metadata (session/login) persistent between reboots.

## Checklist for things done

- [x] Summary of the proposed changes in the PR description
- [x] More detailed description in the commit message(s)
- [x] Commits are squashed into relevant entities - avoid a lot of minimal dev time commits in the PR
- [x] [Contribution guidelines](https://github.com/tiiuae/ghaf/blob/main/CONTRIBUTING.md) followed
- [ ] Ghaf documentation updated with the commit - https://tiiuae.github.io/ghaf/
- [ ] PR linked to architecture documentation and requirement(s) (ticket id)
- [x] Test procedure described (or includes tests). Select one or more:
  - [x] Tested on Lenovo X1 `x86_64`
  - [ ] Tested on Jetson Orin NX or AGX `aarch64`
  - [ ] Tested on Polarfire `riscv64`
- [x] Author has run `make-checks` and it passes
- [x] All automatic Github Action checks pass - see [actions](https://github.com/tiiuae/ghaf/actions)
- [x] Author has added reviewers and removed PR draft status
- [ ] Change requires full re-installation
- [x] Change can be updated with `nixos-rebuild ... switch`

## Instructions for Testing

- [x] List all targets that this applies to:
     It applies only to Lenovo-X1
- [x] Is this a new feature
  - [x] List the test steps to verify:
  1. Run Slack and log in.
  2. Restart comms-vm or reboot the computer
  3. Run Slack againg and make sure the session is preserved
- [ ] If it is an improvement how does it impact existing functionality?

### CODE REVIEW

**Review by vunnyso — APPROVED** [review]

**Comment by milva-unikie** [comment]
Please fill in the description of this PR :)

**Comment by milva-unikie** [comment]
**Tested on Lenovo-X1** (lenovo-x1-carbon-gen11-debug with `nixos-rebuild switch`)
- Slack login information and themes are saved. Slack logs in automatically after restarting comms-vm, after logout/login and after reboot.
- (Element login info is not saved).
- Test-automation passes.

I assume that testing on other platforms is not needed, please let me know if I am wrong about that.

**Comment by unbel13ver** [comment]
> **Tested on Lenovo-X1** (lenovo-x1-carbon-gen11-debug with `nixos-rebuild switch`)
> 
>     * Slack login information and themes are saved. Slack logs in automatically after restarting comms-vm, after logout/login and after reboot.
> 
>     * (Element login info is not saved).
> 
>     * Test-automation passes.
> 
> 
> I assume that testing on other platforms is not needed, please let me know if I am wrong about that.

This changes touches every device than supports business-vm. I am not sure if there are any except of Lenovo-X1.

**Review by vilvo — APPROVED** [review]

**Comment by milva-unikie** [comment]
> > I assume that testing on other platforms is not needed, please let me know if I am wrong about that.
> 
> This changes touches every device than supports comms-vm. I am not sure if there are any except of Lenovo-X1.

Lenovo-X1 is the only one where we have comms-vm at the moment.

**Review by brianmcgillion — APPROVED** [review]

**Pull request merged**
