### PR TITLE
logging: Update the logging server endpoint

### PR DESCRIPTION
**Pull request by vunnyso**
With updated server endpoint url, loki will be using https with basic auth. Access using insecure ip:port and http no longer possible.

## Checklist for things done

- [x] Summary of the proposed changes in the PR description
- [x] More detailed description in the commit message(s)
- [x] Commits are squashed into relevant entities - avoid a lot of minimal dev time commits in the PR
- [x] [Contribution guidelines](https://github.com/tiiuae/ghaf/blob/main/CONTRIBUTING.md) followed
- [ ] Ghaf documentation updated with the commit - https://tiiuae.github.io/ghaf/
- [ ] PR linked to architecture documentation and requirement(s) (ticket id)
- [x] Test procedure described (or includes tests). Select one or more:
  - [x] Tested on Lenovo X1 `x86_64`
  - [ ] Tested on Jetson Orin NX or AGX `aarch64`
  - [ ] Tested on Polarfire `riscv64`
- [ ] Author has run `nix flake check --accept-flake-config` and it passes
- [x] All automatic Github Action checks pass - see [actions](https://github.com/tiiuae/ghaf/actions)
- [x] Author has added reviewers and removed PR draft status

## Testing

**Prerequisite:** 
Depends on https://github.com/tiiuae/ghaf-infra/pull/207 to deployed on server (Now its Merged and Deployed).

**What can be checked?**
Need to identify if there is more frequent journal logs from system with this change and check if any other issues found.

### CODE REVIEW

**Review by brianmcgillion — APPROVED** [review]

**Comment by brianmcgillion** [comment]
image

**Comment by brianmcgillion** [comment]
the gap shows that the messages stopped when the new server hardening was deployed and now it is active again after these changes are applied to the device image

**Comment by brianmcgillion** [comment]
image

**Comment by brianmcgillion** [comment]
it seems that there is a lot more traffic being created in the `net-vm `after the change. the left side of the image was the status with pr #701. the break is when the server hardening was deployed. the right side is with this #700 applied and starting to log.

**Review by vilvo — APPROVED** [review]

**Comment by vunnyso** [comment]
> it seems that there is a lot more traffic being created in the `net-vm `after the change. the left side of the image was the status with pr #701. the break is when the server hardening was deployed. the right side is with this #700 applied and starting to log.

I have tried on my setup I have noticed only minor spikes in `net-vm` with #700 change. 

image

**Comment by leivos-unikie** [comment]
Test results:
- All apps launch
- ci-test-automation pass

Regarding traffic caused by logging I tried `iftop -t -s 300 > iftop.txt` in admin-vm:

Listening on ethint0
   # Host name (port/service if enabled)            last 2s   last 10s   last 40s cumulative
--------------------------------------------------------------------------------------------
   1 admin-vm-debug                           =>         0b        93b        67b     2.15KB
     zathura-vm-debug                         <=         0b       864b       452b     11.5KB
   2 admin-vm-debug                           =>         0b        93b        67b     2.15KB
     appflowy-vm-debug                        <=         0b       863b       451b     11.6KB
   3 admin-vm-debug                           =>         0b        93b        67b     2.15KB
     element-vm-debug                         <=         0b       854b       449b     11.5KB
   4 239.0.0.114                              =>         0b         0b         0b         0B
     element-vm                               <=       496b       298b       260b     9.14KB
   5 admin-vm-debug                           =>         0b        83b        62b       852B
     ghaf-host-debug                          <=         0b        83b        62b     1.36KB
   6 admin-vm-debug                           =>         0b         0b        67b     2.15KB
     gala-vm-debug                            <=         0b         0b       449b     11.5KB
   7 admin-vm-debug                           =>         0b         0b        67b     3.27KB
     net-vm-debug                             <=         0b         0b       347b     16.6KB
   8 admin-vm                                 =>         0b         0b         0b         0B
     net-vm                                   <=         0b         0b        84b       422B
   9 admin-vm                                 =>         0b         0b        66b       332B
     8.8.4.4                                  <=         0b         0b         0b         0B
  10 admin-vm                                 =>         0b         0b        29b       144B
     1.1.1.1                                  <=         0b         0b         0b         0B
--------------------------------------------------------------------------------------------
Total send rate:                                         0b       362b       494b
Total receive rate:                                    496b     2.89Kb     2.49Kb
Total send and receive rate:                           496b     3.25Kb     2.98Kb
--------------------------------------------------------------------------------------------
Peak rate (sent/received/total):                     2.08Kb     13.2Kb     14.9Kb
Cumulative (sent/received/total):                    43.7KB     95.7KB      139KB
============================================================================================

In addition:
- Logging doesn't seem to have any effect on performance
- However performance tests can be seen in the log volumes, e.g. as spikes for each vm. Especially during performance tests on VMs net-vm log volume drops down to ~40 (it has been normally quite steadily around 170 after boot).
- If I do sudo systemctl restart microvm@net-vm.service net-vm log volume drops from ~170 to ~40 (until next boot).

**Review by brianmcgillion — APPROVED** [review]

**Pull request merged**
