### PR TITLE
Refactor VM and application definitions

### PR DESCRIPTION
**Pull request by nesteroff**
## Description of changes

This is an attempt to slightly refactor the application definitions to make it easier to add and remove applications. Currently, adding and removing applications is not straightforward because it requires editing multiple locations to add a launcher, GIVC configuration, etc.

Here are the main changes:
- Virtualized applications are now defined within AppVM configurations in modules/reference/appvms.
- Non-virtualized apps that run in the GUIVM are defined in modules/reference/desktop.
- All dependencies are now configured automatically.
- The "Open in Normal Browser" plugin configuration and Element desktop configuration have been moved to program modules to clean up AppVM configs.
- The PAC code and Firewall settings have been moved to separate modules.

## Checklist for things done

- [x] Summary of the proposed changes in the PR description
- [ ] More detailed description in the commit message(s)
- [x] Commits are squashed into relevant entities - avoid a lot of minimal dev time commits in the PR
- [x] [Contribution guidelines](https://github.com/tiiuae/ghaf/blob/main/CONTRIBUTING.md) followed
- [ ] Ghaf documentation updated with the commit - https://tiiuae.github.io/ghaf/
- [ ] PR linked to architecture documentation and requirement(s) (ticket id)
- [x] Test procedure described (or includes tests). Select one or more:
  - [x] Tested on Lenovo X1 `x86_64`
  - [ ] Tested on Jetson Orin NX or AGX `aarch64`
  - [ ] Tested on Polarfire `riscv64`
- [ ] Author has run `make-checks` and it passes
- [x] All automatic Github Action checks pass - see [actions](https://github.com/tiiuae/ghaf/actions)
- [x] Author has added reviewers and removed PR draft status
- [ ] Change requires full re-installation
- [ ] Change can be updated with `nixos-rebuild ... switch`

## Instructions for Testing

This PR does not introduce new functionality as it is mostly refactoring to make it easier to define virtual machines and applications. Overall testing is probably required to ensure all applications still work especially those in the business-vm.

### CODE REVIEW

**Comment by brianmcgillion** [comment]
502 bad gateway error when accessing outlook. teams works

**Comment by brianmcgillion** [comment]
pdf not being sent to the pdf vm for opening. it opens in the untrusted browser tab not downloaded and opened with the xdg-handler.

**Comment by milva-unikie** [comment]
> pdf not being sent to the pdf vm for opening. it opens in the untrusted browser tab not downloaded and opened with the xdg-handler.

Same with Chrome and comms-vm. That is the only issue I found on X1.

Other than that everything seems to be good. Test-automation passes.

**Comment by brianmcgillion** [comment]
also it seems that the shutdown and reboot are not working.

**Comment by leivos-unikie** [comment]
Checked that ci-test-automation succeeds for Orin-AGX, apps launch and power menu works.

Was testing on other targets necessary?

**Comment by nesteroff** [comment]
> Was testing on other targets than x1 really necessary?

Thanks for testing. This mainly affects laptop targets but it's good to know that AGX works fine.

**Comment by nesteroff** [comment]
The PDF issue should be fixed now.

**Review by brianmcgillion — APPROVED** [review]

**Comment by brianmcgillion** [comment]
pdf working, teams and outlook also working.

**Comment by milva-unikie** [comment]
I also confirmed with X1 that pdf files and connections in business-vm work now.

**Pull request merged**
