### PR TITLE
move all hardware related modules inside hardware folder

### PR DESCRIPTION
**Pull request by Kamarjam**
At the moment hardware configurations are located in two places. Right place for them should be inside modules/hardware as the documentation points out. Also folder names inside hardware folder are little bit confusing so fixing that as well.

## Checklist for things done

- [X] Summary of the proposed changes in the PR description
- [ ] More detailed description in the commit message(s)
- [X] Commits are squashed into relevant entities - avoid a lot of minimal dev time commits in the PR
- [X] [Contribution guidelines](https://github.com/tiiuae/ghaf/blob/main/CONTRIBUTING.md) followed
- [ ] Ghaf documentation updated with the commit - https://tiiuae.github.io/ghaf/
- [ ] PR linked to architecture documentation and requirement(s) (ticket id)
- [ ] Test procedure described (or includes tests). Select one or more:
  - [ ] Tested on Lenovo X1 `x86_64`
  - [ ] Tested on Jetson Orin NX or AGX `aarch64`
  - [ ] Tested on Polarfire `riscv64`
- [X] Author has run `make-checks` and it passes
- [X] All automatic Github Action checks pass - see [actions](https://github.com/tiiuae/ghaf/actions)
- [X] Author has added reviewers and removed PR draft status

## Instructions for Testing

no new functionality but needs to be tested on all platforms

### CODE REVIEW

**Comment by brianmcgillion** [comment]
Thanks @Kamarjam. I think that we want to keep the modules section generic, so all the x1 specific and ... should be moved out eventually and leave only things like enablers for the various hw e.g. generic-x86.

As all of what you moved there are reference HW. i had been planning to move all that HW under `modules/reference/hardware` to highlight that they are just examples of how to enable Ghaf on a given board. so how about moving those there instead of the modules/hardware.

Eventually the Idea could be to move the reference section to a downstream project that inherits Ghaf and then setsup those reference projects.

**Comment by Kamarjam** [comment]
> Thanks @Kamarjam. I think that we want to keep the modules section generic, so all the x1 specific and ... should be moved out eventually and leave only things like enablers for the various hw e.g. generic-x86.
> 
> As all of what you moved there are reference HW. i had been planning to move all that HW under `modules/reference/hardware` to highlight that they are just examples of how to enable Ghaf on a given board. so how about moving those there instead of the modules/hardware.
> 
> Eventually the Idea could be to move the reference section to a downstream project that inherits Ghaf and then setsup those reference projects.

Makes sense. That would leave "common" and "x86_64-generic" folders inside "modules/hardware" . So new hardware folder under reference and move laptop.nix also there

**Comment by vilvo** [comment]
>. So new hardware folder under reference and move laptop.nix also there

I'll review after you've implemented the proposed structural changes.

**Review by vilvo — APPROVED** [review]
LGTM. As a general note, please check all PR description checklist items that apply - e.g.:
[x] Commits are squashed into relevant entities - avoid a lot of minimal dev time commits in the PR - (you've done this, thanks for updating single commit)
[x] Author has run `make-checks` and it passes (I'm running it now...)
      (if not familiar - `nix develop .#default` and `make-checks`)
 [x] All automatic Github Action checks pass - see [actions](https://github.com/tiiuae/ghaf/actions)
 [x] Author has added reviewers and removed PR draft status (you've done this, except checking this checklist item ;-) )

**Comment by vilvo** [comment]
`make-checks` passes

**Comment by leivos-unikie** [comment]
Tested packages.x86_64-linux.microchip-icicle-kit-debug-from-x86_64 build on icicle-kit
- ci-test-automation pass
- didn't find any issues.

**Comment by johannarautanen** [comment]
Tested with Orin-AGX (commit: 6fbe439e6edc6b01885025b318e156f5f85290a5). Flash to EMMC.

-Test-automation passes
- All apps open
- No issues found

Tested with Orin-NX(commit: 6fbe439e6edc6b01885025b318e156f5f85290a5)
-Test-automation passes
- All apps open
- No issues found

**Comment by leivos-unikie** [comment]
Tested packages.x86_64-linux.nvidia-jetson-orin-nx-debug-from-x86_64 on Orin NX
- Test automation ok
- Apps launch
- No issues found

**Comment by johannarautanen** [comment]
Tested Cross-compile Orin-AGX (commit: https://github.com/tiiuae/ghaf/commit/6fbe439e6edc6b01885025b318e156f5f85290a5). Flash to EMMC.

- Test automation ok
- All apps open
- No issues found that prevent testing or using.

There was on difference to native Orin-AGX build, extra(?) '$(mktemp -d)'-folder shown under ghaf-host after flashing.
That doesn't prevent testing or using.
Screenshot from 2024-09-05 11-08-24

**Comment by milva-unikie** [comment]
> Tested Cross-compile Orin-AGX (commit: [6fbe439](https://github.com/tiiuae/ghaf/commit/6fbe439e6edc6b01885025b318e156f5f85290a5)). Flash to EMMC.
> 
>     * Test automation ok
> 
>     * All apps open
> 
>     * No issues found that prevent testing or using.
> 
> 
> There was on difference to native Orin-AGX build, extra(?) '$(mktemp -d)'-folder shown under ghaf-host after flashing. That doesn't prevent testing or using. Screenshot from 2024-09-05 11-08-24

I believe the extra folder was added already in [here](https://github.com/tiiuae/ghaf/commit/15f2fd623670438624b311813b0353bf036cc875#diff-6398781fcac930532f0f28f909f15f45b2d5f2d3bcb9d8dfab24f5e916e6a879R89), so it is not because of this pr.

**Pull request merged**
