### PR TITLE
Add warning about aarch64-linux flash-script

### PR DESCRIPTION
**Pull request by mikatammi**
## Description of changes

Add warning about aarch64-linux flash-script

## Checklist for things done

- [ ] Summary of the proposed changes in the PR description
- [ ] More detailed description in the commit message(s)
- [ ] Commits are squashed into relevant entities - avoid a lot of minimal dev time commits in the PR
- [ ] [Contribution guidelines](https://github.com/tiiuae/ghaf/blob/main/CONTRIBUTING.md) followed
- [ ] Ghaf documentation updated with the commit - https://tiiuae.github.io/ghaf/
- [ ] PR linked to architecture documentation and requirement(s) (ticket id)
- [X] Test procedure described (or includes tests). Select one or more:
  - [ ] Tested on Lenovo X1 `x86_64`
  - [ ] Tested on Jetson Orin NX or AGX `aarch64`
  - [ ] Tested on Polarfire `riscv64`
- [ ] Author has run `nix flake check --accept-flake-config` and it passes
- [ ] All automatic Github Action checks pass - see [actions](https://github.com/tiiuae/ghaf/actions)
- [ ] Author has added reviewers and removed PR draft status

## Testing

This just adds a warning message to aarch64-linux flash script. Checked that x86 and aarch64 versions of the flash script build.

### CODE REVIEW

**Review by leivos-unikie — COMMENTED** [review]
Nice warning.

I was still thinking... the flake allows build for aarch64-linux hosted version of the flash-script although building on x86 machine. Should this be prevented?

**Comment by leivos-unikie** [comment]
On the other hand attempt to build x86 version on aarch64 produces error:
[ghaf@ghaf-host:~]$ nix build github:mikatammi/ghaf/add_aarch64_flash_script_warning#packages.x86_64-linux.nvidia-jetson-orin-agx-debug-flash-qspi
error: a 'x86_64-linux' with features {} is required to build '/nix/store/88r7cxcy27fhsysc7fzrwhlfc4vpxr2c-builder.pl.drv', but I am a 'aarch64-linux' with features {benchmark, big-parallel, gccarch-armv8-a, kvm, nixos-test}

**Comment by leivos-unikie** [comment]
Tested building and flashing with Orin AGX


1. Flashing Orin NX qspi

nix build github:mikatammi/ghaf/add_aarch64_flash_script_warning#packages.aarch64-linux.nvidia-jetson-orin-nx-debug-flash-qspi

Flash succeeded
[flash-orin-nx-qspi-with-orin-agx.log](https://github.com/tiiuae/ghaf/files/13817213/flash-orin-nx-qspi-with-orin-agx.log)


2. Flashing another Orin AGX qspi

nix build github:mikatammi/ghaf/add_aarch64_flash_script_warning#packages.aarch64-linux.nvidia-jetson-orin-agx-debug-flash-qspi

Flash succeeded.
[flash-agx-qspi-with-agx.log](https://github.com/tiiuae/ghaf/files/13817262/flash-agx-qspi-with-agx.log)


3. Flashing another Orin AGX (qspi and emmc)

nix build github:mikatammi/ghaf/add_aarch64_flash_script_warning#packages.aarch64-linux.nvidia-jetson-orin-agx-debug-flash-script

Flash failed at
[ 336.9697 ] Sending membct and RCM blob
[ 336.9710 ] tegrarcm_v2 --chip 0x23 0 --pollbl --download bct_mem mem_rcm_sigheader.bct.encrypt --download blob blob.bin
[ 336.9717 ] ERROR: failed to open USB 
Error: Return value 8
Command tegrarcm_v2 --chip 0x23 0 --pollbl --download bct_mem mem_rcm_sigheader.bct.encrypt --download blob blob.bin
Failed flashing t186ref.
[flash-agx-with-agx.log](https://github.com/tiiuae/ghaf/files/13817310/flash-agx-with-agx.log)

**Comment by leivos-unikie** [comment]
Tested building and flashing with Orin NX


1. Flashing Orin AGX qspi

nix build github:mikatammi/ghaf/add_aarch64_flash_script_warning#packages.aarch64-linux.nvidia-jetson-orin-nx-debug-flash-qspi

Flash succeeded
[flash-agx-qspi-with-orin-nx.log](https://github.com/tiiuae/ghaf/files/13819099/flash-agx-qspi-with-orin-nx.log)


2. Flashing Orin AGX (qspi + emmc)

nix build github:mikatammi/ghaf/add_aarch64_flash_script_warning#packages.aarch64-linux.nvidia-jetson-orin-agx-debug-flash-script

Build failed with error.

**Review by brianmcgillion — APPROVED** [review]

**Review by brianmcgillion — COMMENTED** [review]
remove approval, till errors understood

**Pull request merged**
