### PR TITLE
Update jetpack-nixos to version matching r35.3.1

### PR DESCRIPTION
**Pull request by mikatammi**

### CODE REVIEW

**Comment by mikatammi** [comment]
Also FYI: update to r35.3.1 now enables OP-TEE and tee-supplicant service

**Comment by mikatammi** [comment]
Please remember to flash everything again after the merge!

**Review by brianmcgillion — APPROVED** [review]
Compiles boots and runs.

It might be worth pushing the head to https://github.com/anduril/jetpack-nixos/commit/5139b8ca8dd3ffeddfac44d361887bf2e306071a

This latest patch enables automatic FW updates.

**Comment by mikatammi** [comment]
> Compiles boots and runs.
> 
> It might be worth pushing the head to [anduril/jetpack-nixos@5139b8c](https://github.com/anduril/jetpack-nixos/commit/5139b8ca8dd3ffeddfac44d361887bf2e306071a)
> 
> This latest patch enables automatic FW updates.

@brianmcgillion Let's leave this for another PR, something broke when I tried to update jetpack-nixos in flake.lock, and the flashing script broke

**Pull request merged**
