### PR TITLE
wifi-connector: Support nmcli interface

### PR DESCRIPTION
**Pull request by unbel13ver**
Now when NetworkManager is in use for NetVM, edit the script to use nmcli to avoid any conflicts.

### CODE REVIEW

**Comment by riskuuse** [comment]
As NetworkManager is in use only in lenovo X1 target, wouldn't this brake wifi-connector for other targets?

**Comment by unbel13ver** [comment]
> As NetworkManager is in use only in lenovo X1 target, wouldn't this brake wifi-connector for other targets?

Voi ei, it will!!!

**Comment by riskuuse** [comment]
Looks good to me now. Tested on X1 but not on any other targets.

**Review by riskuuse — APPROVED** [review]
Looks good to me now. Tested on X1 but not on any other targets.

**Review by mikatammi — APPROVED** [review]

**Pull request merged**
