### PR TITLE
reference: configuration support for Orin NX

### PR DESCRIPTION
**Pull request by vilvo**

### CODE REVIEW

**Comment by vilvo** [comment]
The kernel build fails:
```
❯ nix build .#packages.aarch64-linux.nvidia-jetson-orin-nx-debug
warning: Git tree '/home/vilvo/ghaf' is dirty
error: build of '/nix/store/xsyhyw6m93dm3wl7ppivwi8w1pjwbc0c-linux-5.10.104.drv' on 'ssh://vilvo@192.168.1.195' failed: builder for '/nix/store/xsyhyw6m93dm3wl7ppivwi8w1pjwbc0c-linux-5.10.104.drv' failed with exit code 2;
       last 10 log lines:
       > make[1]: *** Waiting for unfinished jobs....
       > /nix/store/ahj524ij9n6700yzqj03adhq5ibscsaw-linux-5.10.104-dev/lib/modules/5.10.104/source/scripts/Makefile.build:69: './nvmap.ko' will not be built even though obj-m is specified.
       > /nix/store/ahj524ij9n6700yzqj03adhq5ibscsaw-linux-5.10.104-dev/lib/modules/5.10.104/source/scripts/Makefile.build:70: You cannot use subdir-y/m to visit a module Makefile. Use obj-y/m instead.
       > /nix/store/5zfaafzpdi70lrib7a4rk5km6w381l91-binutils-2.40/bin/ld: warning: -z relro ignored
       > /nix/store/5zfaafzpdi70lrib7a4rk5km6w381l91-binutils-2.40/bin/ld: warning: -z relro ignored
       > /nix/store/5zfaafzpdi70lrib7a4rk5km6w381l91-binutils-2.40/bin/ld: warning: -z relro ignored
       > /nix/store/5zfaafzpdi70lrib7a4rk5km6w381l91-binutils-2.40/bin/ld: warning: -z relro ignored
       > /nix/store/5zfaafzpdi70lrib7a4rk5km6w381l91-binutils-2.40/bin/ld: warning: -z relro ignored
       > /nix/store/5zfaafzpdi70lrib7a4rk5km6w381l91-binutils-2.40/bin/ld: warning: -z relro ignored
       > make: *** [/nix/store/ahj524ij9n6700yzqj03adhq5ibscsaw-linux-5.10.104-dev/lib/modules/5.10.104/source/Makefile:203: __sub-make] Error 2
```
It fails with above error before and after the rebase and adapting the new module system. 

The build succeeded on Friday before [571acec](https://github.com/tiiuae/ghaf/pull/182/commits/571acec4de3ed46e7aa22aa22ebb0127325fa5ad)

**Review by brianmcgillion — DISMISSED** [review]
What is the actual delta from the AGX. Do we need to duplicate everything, or is there a possibility to just pass the SOM name to the derivation / module and have it build ?

**Comment by vilvo** [comment]
> What is the actual delta from the AGX. Do we need to duplicate everything, or is there a possibility to just pass the SOM name to the derivation / module and have it build ?

There's different device trees to address different NICs (AGX passthrough to netvm with wifi and NX passthrough with ethernet (does not have wifi) so those patches had to be adapted.
Flashing is different and @emrahbillur is working on it - though the flashing support is not critical as this can be used with USB/SSD by flashing the device when the kernel build break is addressed.

Given those changes, passing only the SOM name might be possible but can get messy (even NVIDIA has differentiated certain files in the BSP and we must address those changes within nixification). Given that, I would focus first on functionality to enable using this in an external repo.

Beyond that, I tested this last week to sport the full Weston.

Please do not review this yet, it's marked as a draft and duplications still must be addressed. I opened the PR and made it draft to make the work visible.

**Review by mikatammi — CHANGES_REQUESTED** [review]
Generally I don't like the copy-paste coding approach in this PR. We should conditionalize all the stuff under the same modules/hardware/nvidia-jetson-orin module, and then using the `ghaf.hardware.nvidia.orin.somType = "nx";` option select that we want the NX variant.

**Comment by mikatammi** [comment]
Also there is this other "initrd flashing script" in jetpack-nixos we could use for Orin NX stuff. When I checked I was unable to use the basic "low level" flashing tool with NVME drive.

**Comment by mikatammi** [comment]
There is discussion about the flashing script issue here:
* https://github.com/anduril/jetpack-nixos/issues/33
* https://github.com/anduril/jetpack-nixos/pull/32

We could try to adapt the initrd-based flashing that was added in this PR. I don't know how it manages the flashing of the whole root partition, never tested these yet.
* https://github.com/anduril/jetpack-nixos/pull/58/files

**Comment by vilvo** [comment]
> Thanks @emrahbillur - builds again. I'll test functionally the next week. 

`netvm` still fails to start:
```
Jun 22 13:16:20 ghaf-host microvm-pci-devices@netvm-nvidia-jetson-orin-nx-debug[1131]: /sys/bus/pci/devices/0004:00:00.0 /var/lib/microvms/netvm-nvidia-jetson-orin-nx-debug
Jun 22 13:16:20 ghaf-host microvm-pci-devices@netvm-nvidia-jetson-orin-nx-debug[1131]: Making VFIO device 7 accessible for user
Jun 22 13:16:20 ghaf-host kernel: vfio-pci: probe of 0004:00:00.0 failed with error -22
Jun 22 13:16:20 ghaf-host microvm-pci-devices@netvm-nvidia-jetson-orin-nx-debug[1136]: chown: cannot access '/dev/vfio/7': No such file or directory
Jun 22 13:16:20 ghaf-host systemd[1]: microvm-pci-devices@netvm-nvidia-jetson-orin-nx-debug.service: Main process exited, code=exited, status=1/FAILURE
```
Both serial debug and eth+dhcp for host access work.

**Comment by vilvo** [comment]
Closed based on @brianmcgillion guidance to do PRs from personal forks instead.

**Pull request closed without merging**
