### PR TITLE
Render window borders on the guivm side instead of the appvm

### PR DESCRIPTION
**Pull request by nesteroff**
- Windows borders are rendered on the compositor side.
- Border size and color can be configured in the appvm options.
- All waypipe processes are completely separated; each app gets its own instance of waypipe and vsockproxy.

### CODE REVIEW

**Comment by mikatammi** [comment]
@nesteroff Please rebase the branch, otherwise LGTM. Didn't test yet as the patch didn't apply cleanly

**Comment by leivos-unikie** [comment]
Could the border size increase outside the actual window?

IMG_2297

**Comment by leivos-unikie** [comment]
In zathura default border size (5) is already disturbing, the border is blocking view to the command line at the bottom.

IMG_2298
Here chromium with border size 3 and zathura with border size 5.

**Comment by nesteroff** [comment]
Drawing a border outside of the actual window is quite hard to implement in Waypipe. We will need to keep track of the original window size, send increased size to the compositor, reallocate buffers, copy data and etc. One of the things that you can do is to use transparency. For example this is a semi-transparent red color: #FF000080.

Overall, drawing window borders in Waypipe is a temporary solution. Dmitry is currently implementing this feature in the compositor where it will be possible to change the color of the original window decorations. We plan to switch to this implementation once it's ready.

**Comment by leivos-unikie** [comment]
> Drawing a border outside of the actual window is quite hard to implement in Waypipe. We will need to keep track of the original window size, send increased size to the compositor, reallocate buffers, copy data and etc. One of the things that you can do is to use transparency. For example this is a semi-transparent red color: #FF000080.
> 
> Overall, drawing window borders in Waypipe is a temporary solution. Dmitry is currently implementing this feature in the compositor where it will be possible to change the color of the original window decorations. We plan to switch to this implementation once it's ready.

I agree, no need to put more effort on this. The new implementation looks promising.

**Comment by nesteroff** [comment]
Closing this one since the plan is to switch to labwc and change the colors of native window decorations.

**Pull request closed without merging**
