### PR TITLE
switch to nixpkgs branch, which contains recent fixes

### PR DESCRIPTION
**Pull request by avnik**
This branch contain fixes for clang (not yet accepted into stable), and fixes for perl-Module-Build

### CODE REVIEW

**Comment by vilvo** [comment]
Would you please add instructions on how you tested cross-compilation with this branch and ghaf? E.g.
```
vilvo in 🌐 blip in ghaf (35946eb) [!?] took 4m11s
❯ uname -a
Linux blip 6.3.7 #1-NixOS SMP PREEMPT_DYNAMIC Fri Jun  9 08:48:26 UTC 2023 x86_64 GNU/Linux
vilvo in 🌐 blip in ghaf (35946eb) [!?] took 4m11s
❯ nix build .#packages.aarch64-linux.nvidia-jetson-orin-debug
error: a 'aarch64-linux' with features {} is required to build '/nix/store/a277pdxq36gmw2vzkjvjk4c593qdn0r1-absolute_shlib_path.patch.drv', but I am a 'x86_64-linux' with features {benchmark, big-parallel, kvm, nixos-test}
```
replaced with the `nix build ...` you've used. 
Also, I think we could approach the merge to ghaf with having a flake target that uses this input instead of replacing this input for all the targets.

**Comment by avnik** [comment]
I use `nix build -L ".#nvidia-jetson-orin-debug-from-x86_64-flash-script" --cores 16 `
I would think, how to make separate input, but all these changes shouldn't affect emulated build (with remote builder and/or qemu), even would be nice to check that they won't break anything.

**Comment by vilvo** [comment]
> I use `nix build -L ".#nvidia-jetson-orin-debug-from-x86_64-flash-script" --cores 16 `

I think this uses `.#packages.x86_64-linux`-target instead of `aarch64-linux`? 
 
> I would think, how to make separate input, but all these changes shouldn't affect emulated build (with remote builder and/or qemu), even would be nice to check that they won't break anything.

Hmm, are we talking about the same thing. Emulated builds use native toolchains and emulate the arch with QEMU where remote builders use native toolchains on target arch. 
For cross-compilation, we need cross-compilation toolchains - namely `x86_64` cross-compilation toolchains to produce `aarch64` binaries.
These approaches will produce different derivations because of different toolchains.

**Comment by vilvo** [comment]
In particular, with real cross-compilation we can't and shouldn't assume `binfmt`

**Comment by avnik** [comment]
> > I use `nix build -L ".#nvidia-jetson-orin-debug-from-x86_64-flash-script" --cores 16 `
> 
> I think this uses `.#packages.x86_64-linux`-target instead of `aarch64-linux`?
> 
This code path inject `buildPackage.system = "x86_64-linux"` here https://github.com/tiiuae/ghaf/blob/main/targets/nvidia-jetson-orin.nix#L89 (what turn on cross building)

> > I would think, how to make separate input, but all these changes shouldn't affect emulated build (with remote builder and/or qemu), even would be nice to check that they won't break anything.
> 
> Hmm, are we talking about the same thing. Emulated builds use native toolchains and emulate the arch with QEMU where remote builders use native toolchains on target arch. For cross-compilation, we need cross-compilation toolchains - namely `x86_64` cross-compilation toolchains to produce `aarch64` binaries. These approaches will produce different derivations because of different toolchains.

Yes, we need test these builds, that patched nixpkgs don't affect them. They even shouldn't rebuild from patches.

**Comment by vilvo** [comment]
> > > I use `nix build -L ".#nvidia-jetson-orin-debug-from-x86_64-flash-script" --cores 16 `
> > 
> > 
> > I think this uses `.#packages.x86_64-linux`-target instead of `aarch64-linux`?
> 
> This code path inject `buildPackage.system = "x86_64-linux"` here https://github.com/tiiuae/ghaf/blob/main/targets/nvidia-jetson-orin.nix#L89 (what turn on cross building)

Thanks for clarifying.

> > > I would think, how to make separate input, but all these changes shouldn't affect emulated build (with remote builder and/or qemu), even would be nice to check that they won't break anything.
> > 
> > 
> > Hmm, are we talking about the same thing. Emulated builds use native toolchains and emulate the arch with QEMU where remote builders use native toolchains on target arch. For cross-compilation, we need cross-compilation toolchains - namely `x86_64` cross-compilation toolchains to produce `aarch64` binaries. These approaches will produce different derivations because of different toolchains.
> 
> Yes, we need test these builds, that patched nixpkgs don't affect them. They even shouldn't rebuild from patches.

While testing on `x86_64` I get:
```
❯ nix build -L ".#nvidia-jetson-orin-debug-from-x86_64-flash-script" --cores 16 --builders ''
error (ignored): error: cannot unlink '/tmp/nix-build-abseil-cpp-aarch64-unknown-linux-gnu-20210324.2.drv-0/source/absl/time/internal/cctz/testdata/zoneinfo': Directory not empty
error: a 'aarch64-linux' with features {} is required to build '/nix/store/a277pdxq36gmw2vzkjvjk4c593qdn0r1-absolute_shlib_path.patch.drv', but I am a 'x86_64-linux' with features {benchmark, big-parallel, kvm, nixos-test}
(use '--show-trace' to show detailed location information)
```

**Comment by vilvo** [comment]
> Also it still require disable netvm, or manually inject cross-statement to netvm's config

That note with details could be added as well for other verifiers in the CI etc.
 
> Also have no idea if `--builders ""` affect on this.

I tested.

Without it checks the availability of my configured remote builders (made them NA):
```required (system, features): (aarch64-linux, [])
2 available machines:
(systems, maxjobs, supportedFeatures, mandatoryFeatures)
([aarch64-linux], 1, [benchmark, big-parallel, kvm, nixos-test], [])
([aarch64-linux], 4, [benchmark, big-parallel, kvm, nixos-test], [])
```
With, it does not check the remote builders.

**Comment by vilvo** [comment]
> (anyway, I'll fix flake.lock conflict first)

Please also address https://github.com/tiiuae/ghaf/pull/211/checks?check_run_id=14741934876

**Comment by avnik** [comment]
Done.
Do you remember option to enable "Signed-Off" permanently?

**Comment by avnik** [comment]
> > Also it still require disable netvm, or manually inject cross-statement to netvm's config
> 
> That note with details could be added as well for other verifiers in the CI etc.
> 

I still experimenting, how to inject these cross statements only on demand.
(as parts of my flake-parts studies)

> > Also have no idea if `--builders ""` affect on this.
> 
> I tested.
> 
> Without it checks the availability of my configured remote builders (made them NA):
> 

Good to know.
BTW, I should try enable emulated builds on second machine, and ensure that they are turnable-off by this option.

**Comment by avnik** [comment]
Also, I not sure, if it easy to add this branch as separate input (too much conditional code need to be added). But probably I can add a template flake.nix in folder, using this branch and `inputs.nixpkgs.follows = "this-branch"` feature. Let me check, if it works

**Comment by avnik** [comment]
@vilvo I add a temporary commit to inject cross-statements to netvm, to allow test as well as illustrate how to fix microvm.
At least `nix build -L ".#nvidia-jetson-orin-debug-from-x86_64-flash-script" --cores 16` works for me, and going up to start build chromium.  (I'll probably try to build it overnight)

**Comment by vilvo** [comment]
> @vilvo I add a temporary commit to inject cross-statements to netvm, to allow test as well as illustrate how to fix microvm. 

Thanks. Further development to pass the cross-statements from the target will be needed but serves the purpose illustrating the approach. E.g. `hostPlatform.system = "riscv64-linux"` will be needed for #215 reference support. 

> At least `nix build -L ".#nvidia-jetson-orin-debug-from-x86_64-flash-script" --cores 16` works for me, and going up to start build chromium. (I'll probably try to build it overnight)

I tried to say yesterday that please drop the graphics support for now - building the demo apps not only takes plenty time but also is not necessary for the initial cross-compilation support. You can use ghaf options to drop both weston and the demo apps. https://tiiuae.github.io/ghaf/ref_impl/modules_options.html#ghafgraphicswestonenable
 Host + netvm would be good starting point for the initial cross-compilation support.

**Comment by avnik** [comment]
@vilvo FYI with recent @mikatammi update, that additional commit probably unneeded, so I try to revert/rebase, if it works. I update this branch in 2-3 mins

**Comment by avnik** [comment]
@vilvo I rebased to include recent  Mika's changes, it now builds w/o additional statements. But we need to wrap windows+qemu under demoApp conditional, because it pull broken zenity. (but netvm builds btw)

**Comment by avnik** [comment]
@vilvo Well, with new merged nixos-23.05 my branch build until failure during `nixos-disk-image` (which is probably expected).  I build with `nix build -L ".#nvidia-jetson-orin-debug-from-x86_64-flash-script" --cores 16` and `enableDemoApplications = false`

@mikatammi we need to coordinate, how to bump nixpkgs then, would be nice to  move this `nixpkgs/ghaf-23.05` under tiiuae project, and update by merging.

**Comment by avnik** [comment]
Replaced by #224

**Pull request closed without merging**
