### PR TITLE
desktop: Add descriptions for launcher applications

### PR DESCRIPTION
**Pull request by humaidq-tii**
## Description of changes

- Add descriptions for launcher applications
- It includes the VM name in case it is launched in a VM.

In the future, category tabs may be added. Currently with nwg-drawer the categories are hard-coded, so that has to be changed to support category per-VM or other custom categories.

## Checklist for things done

- [x] Summary of the proposed changes in the PR description
- [x] More detailed description in the commit message(s)
- [x] Commits are squashed into relevant entities - avoid a lot of minimal dev time commits in the PR
- [x] [Contribution guidelines](https://github.com/tiiuae/ghaf/blob/main/CONTRIBUTING.md) followed
- [ ] Ghaf documentation updated with the commit - https://tiiuae.github.io/ghaf/
- [ ] PR linked to architecture documentation and requirement(s) (ticket id)
- [x] Test procedure described (or includes tests). Select one or more:
  - [x] Tested on Lenovo X1 `x86_64`
  - [x] Tested on Jetson Orin NX or AGX `aarch64`
  - [ ] Tested on Polarfire `riscv64`
- [x] Author has run `make-checks` and it passes
- [x] All automatic Github Action checks pass - see [actions](https://github.com/tiiuae/ghaf/actions)
- [x] Author has added reviewers and removed PR draft status
- [ ] Change requires full re-installation
- [x] Change can be updated with `nixos-rebuild ... switch`
  - gui-vm will reboot

## Instructions for Testing

- [x] List all targets that this applies to:
  - Any target that has desktop environment and launcher
  -  Lenovo X1
  - Jetson Orin
- [x] Is this a new feature
  - [x] List the test steps to verify:
    - Boot into desktop
    - Hover on each launcher entry
    - Each should have an accurate description shown, with correct VM listed (in case it is a VM application).
- [x] If it is an improvement how does it impact existing functionality?
  - Improves usability

### CODE REVIEW

**Review by brianmcgillion — APPROVED** [review]

**Review by vunnyso — APPROVED** [review]

**Comment by johannarautanen** [comment]
NVIDIA Jetson AGX Orin native, booted Orin AGX from eMMC
Check with commit: 0480684964a5b52060629346e1d13ffdd6750f33

In Orin-AGX each launcher entry has accurate description: "General Messing Application", "Web browser", "Lock Session", "Quit Applications & Log Out", "PDF Viewer Application", "System Terminal" and "Virtualized Windows System"


Automation cases: ok
Launching apps and manual regression tests: ok

**Comment by johannarautanen** [comment]
NVIDIA Jetson NX Orin native, booted Orin NX from USB flash drive
Check with commit: https://github.com/tiiuae/ghaf/commit/0480684964a5b52060629346e1d13ffdd6750f33

In Orin-NX each launcher entry has accurate description: "General Messing Application", "Web browser", "Lock Session", "Quit Applications & Log Out", "PDF Viewer Application", "System Terminal" and "Virtualized Windows System"

Automation cases: ok
Launching apps and manual regression tests: ok

**Comment by johannarautanen** [comment]
Tested with lenovo-x1, booted from USB SSD
Check with commit: https://github.com/tiiuae/ghaf/commit/0480684964a5b52060629346e1d13ffdd6750f33
Change worked with "nixos-rebuild ... switch"

In lenovo-X1 each launcher entry has accurate description ie: [Comms] "General Messing Application", [Chromium] Isolated General Browsing", "Lock Session", "Quit Applications & Log Out", [Zathura]"PDF Viewer Application", "System Terminal", [Business]Isolated Trusted Browsing, [GALA] Secure Android-in-the-Cloud, [AppFlowy]Productivity & Note-Taking Application...


Automation cases: ok
Launching apps: ok

**Comment by johannarautanen** [comment]
NVIDIA Jetson AGX Orin cross compile, booted Orin AGX from eMMC
Check with commit: https://github.com/tiiuae/ghaf/commit/0480684964a5b52060629346e1d13ffdd6750f33

In Orin-AGX each launcher entry has accurate description: "General Messing Application", "Web browser", "Lock Session", "Quit Applications & Log Out", "PDF Viewer Application", "System Terminal" and "Virtualized Windows System"

Launching apps: ok

**Pull request merged**
