### PR TITLE
common: Create options for applications, other fixes

### PR DESCRIPTION
**Pull request by humaidtii**
This creates a new option `ghaf.programs.<name>`, which allows us to configure applications across targets and whether they run inside a VM or not.

This also fixes Chromium border glitch, and Element border colour (SP-4645 & SP-4644).

## Description of changes

- Add program option for Zathura, fixes clipboard issue also on Orin.
- Add program option for Chromium
  - Fixes border glitch when unmaximising application.
  - Chromium on Orin should now behave similarly to X1 carbon.
- Fix Element border.
- Fix duplicate icons on Orin.

## Checklist for things done

- [x] Summary of the proposed changes in the PR description
- [x] More detailed description in the commit message(s)
- [x] Commits are squashed into relevant entities - avoid a lot of minimal dev time commits in the PR
- [x] [Contribution guidelines](https://github.com/tiiuae/ghaf/blob/main/CONTRIBUTING.md) followed
- [ ] Ghaf documentation updated with the commit - https://tiiuae.github.io/ghaf/
- [x] PR linked to architecture documentation and requirement(s) (ticket id)
- [x] Test procedure described (or includes tests). Select one or more:
  - [x] Tested on Lenovo X1 `x86_64`
  - [x] Tested on Jetson Orin NX or AGX `aarch64`
  - [ ] Tested on Polarfire `riscv64`
- [ ] Author has run `nix flake check --accept-flake-config` and it passes
- [ ] All automatic Github Action checks pass - see [actions](https://github.com/tiiuae/ghaf/actions)
- [x] Author has added reviewers and removed PR draft status

## Testing

- Chromium can still open PDFs on X1 carbon.
- Chromium unmaximise glitch fixed on X1 carbon.
- Zathura on Orin can now copy to normal clipboard (not primary).
- Element border should be fully coloured.

### CODE REVIEW

**Comment by milva-unikie** [comment]
Chromium is not launching from the icon on X1. The command that previously worked for launching chromium is also not working.
```
[ghaf@chromium-vm:~]$ run-waypipe chromium --enable-features=UseOzonePlatform --ozone-platform=wayland
S687: 13.368508 [src/server.c:719] Spawn failure for 'chromium': No such file or directory
```
It makes testing this PR quite difficult, so I did not yet test much else.

**Comment by johannarautanen** [comment]
**Test results on native Orin-AGX:**

It was possible to copy text from Zathura to terminal with selecting the "Paste"

To Element copying successful with ctrl+v and with "Paste"

In Orin  there is only Firefox-browser available.
To Firefox-browser  you can paste zathura-text with the third(middle) mouse button, is that ok?
And to Firefox-browser you can paste with ctrl+v and with "Paste"


Automated bat-tests OK
All Apps launched
Manual regression test ok.

**Comment by johannarautanen** [comment]
**Test results on native Orin-NX:**

Same kind of results as with AGX:

It was possible to copy text from Zathura to terminal with selecting the "Paste"

To Element copying successful with ctrl+v and with "Paste"

In Orin there is only Firefox-browser available.
**To Firefox-browser you can paste zathura-text with the third(middle) mouse button, is that ok?**
And to Firefox-browser you can paste with ctrl+v and with "Paste"

Automated bat-tests OK
All Apps launched
Manual regression test ok.

**Comment by milva-unikie** [comment]
**Tested on X1**
- Test-automation passes
- All apps launch
- Chromium border does not glitch anymore after unmaximising
- Element border is fixed
- Pdf files can be opened from Chromium to Zathura
- Zathura uses regular clipboard

**Review by brianmcgillion — APPROVED** [review]

**Pull request merged**
