### PR TITLE
Switch to NixOS 23.11

### PR DESCRIPTION
**Pull request by mikatammi**
## Checklist for things done

- [X] Summary of the proposed changes in the PR description
- [X] More detailed description in the commit message(s)
- [X] Commits are squashed into relevant entities - avoid a lot of minimal dev time commits in the PR
- [X] [Contribution guidelines](https://github.com/tiiuae/ghaf/blob/main/CONTRIBUTING.md) followed
- [ ] Ghaf documentation updated with the commit - https://tiiuae.github.io/ghaf/
- [ ] PR linked to architecture documentation and requirement(s) (ticket id)
- [x] Test procedure described (or includes tests). Select one or more:
  - [x] Tested on Lenovo X1 `x86_64`
  - [ ] Tested on Jetson Orin NX or AGX `aarch64`
  - [ ] Tested on Polarfire `riscv64`
- [ ] Author has run `nix flake check --accept-flake-config` and it passes
- [ ] All automatic Github Action checks pass - see [actions](https://github.com/tiiuae/ghaf/actions)
- [ ] Author has added reviewers and removed PR draft status

## Testing

All the basic Robot Framework tests. Test flashing of both native and cross-compiled Jetson Orin flashing scripts

### CODE REVIEW

**Comment by mikatammi** [comment]
This basically has now everything needed for NixOS 23.11 in place. Need to run tests still

**Comment by mikatammi** [comment]
This backport PR needs to fall on to channel to fix the RISC-V build, then we can go:
https://nixpk.gs/pr-tracker.html?pr=271790
Backport PR: https://github.com/NixOS/nixpkgs/pull/271790

Original PR: https://github.com/NixOS/nixpkgs/pull/271707

**Comment by mikatammi** [comment]
Now builds on RISC-V, running tests again for other platforms

**Comment by mikatammi** [comment]
Tested and ready to go in!

**Review by brianmcgillion — APPROVED** [review]

**Comment by brianmcgillion** [comment]
Pushed in to allow hydra to do the needful

**Pull request merged**
