### PR TITLE
Add audio passthrough for audioVM on Lenovo X1 gen10

### PR DESCRIPTION
**Pull request by josa41**
## Description of changes
Audio VM pci passthrough devices for Lenovo X1 gen 10

## Checklist for things done

- [x] Summary of the proposed changes in the PR description
- [x] More detailed description in the commit message(s)
- [x] Commits are squashed into relevant entities - avoid a lot of minimal dev time commits in the PR
- [x] [Contribution guidelines](https://github.com/tiiuae/ghaf/blob/main/CONTRIBUTING.md) followed
- [ ] Ghaf documentation updated with the commit - https://tiiuae.github.io/ghaf/
- [x] PR linked to architecture documentation and requirement(s) (ticket id)
- [ ] Test procedure described (or includes tests). Select one or more:
  - [ ] Tested on Lenovo X1 `x86_64`
  - [ ] Tested on Jetson Orin NX or AGX `aarch64`
  - [ ] Tested on Polarfire `riscv64`
- [ ] Author has run `nix flake check --accept-flake-config` and it passes
- [ ] All automatic Github Action checks pass - see [actions](https://github.com/tiiuae/ghaf/actions)
- [x] Author has added reviewers and removed PR draft status

Tested only on Lenovo X1 gen 11 (that has a bit different pcie devices/config)

## Testing
Tested by playback and audio recording on chromium app
- Integrated mic and speaker works
- 3.5mm headset jack works
- Automatic changing between integrated and 3.5mm jack works
- NOTE USB/Bluetooth audio devices/headsets don't work (yet)
- ElementVM DNS settings has a bug so audio with element VM might not work

### CODE REVIEW

**Comment by josa41** [comment]
Do we have someone with Lenovo X1 gen10 laptop to test this?

**Review by brianmcgillion — APPROVED** [review]

**Review by vilvo — APPROVED** [review]
LGTM. Got no gen10 to verify.

**Comment by mbssrc** [comment]
yes I can probably find one and run this tomorrow

**Review by brianmcgillion — APPROVED** [review]

**Comment by brianmcgillion** [comment]
if it breaks, someone will shout later as noone seems to have the hardware

**Pull request merged**
