### PR TITLE
Add login manager, magnification, reuse.toml, and desktop improvements

### PR DESCRIPTION
**Pull request by humaidq-tii**
- Adds a login manager and a graphical greeter in Ghaf, with option for autologin (by default for now). This removes redundant services such as ghaf-session, and seatd (as replaced with an official NixOS service option).
- Adds magnification in labwc, which can be used for accessibility, development, and demo purposes.
- Switch to reuse.toml. Reuse specification version 3.2 deprecates support of dep5. Also more explicitly define the licenses for patches.
- Improves launcher speed and adds a keybind (super/windows left key). Set time to 24h.
- Improve audio keybindings latency, and desktop theme.
- Run 'autostart' application as systemd user services.

## Description of changes

- Adds greetd login manager
  - This runs as a separate user 'greeter' which is in 'video' group.
  - Use gtkgreet as a greeter, customised to match our style guide.
  - We may switch to something more customisable, such as ReGreet.
  - Uses labwc compositor to run the greeter
  - Brightness controls, alternative keyboard layouts works on the login screen.
  - Not possible to launch Terminal from greeter user.
  - labwc supports multi-monitor well, as well as `wlr-layer-shell-unstable` for gtkgreet.
  - Replace custom seatd service with `services.seatd` as it is now available in NixOS.
  - Set wlroots environment variables using `environment.sessionVariables`.
  - This allows other compositor to work properly, but this PR doesn't add any new compositors.
  - Fix renderer option for Orin (previously it seemed to fallback correctly even with typo).
- Add keybindings for magnification.
  - Super+z for toggling magnification.
  - Super+- for zoom out.
  - Super++ (without pressing Shift) for zoom in.
- Switch to reuse.toml
  - Use reuse.toml instead of dep5 (Debian-style), as it has been deprecated.
  - Keep all license information in `REUSE.toml` so it is easier to define in a single place.
  - Include licenses for the patches included in this repository.
  - License assets for docs under CC-BY-SA-4.0 instead of Apache-2.0.
- Drawer improvements
  - Use nwg-drawer memory resident feature, so it stays in background after login. This improves launcher speed.
  - Adds keybind (windows/Super Left) key for opening drawer.
  - Sets clock to 24h, other cleanup.
- Improve desktop
  - Only right click should show debug menu, on debug builds.
  - Added drop shadows for windows.
  - Mouse should use regular scrolling instead of natural. Touchpad uses natural scrolling.
  - Removal of 'Ghaf Platform' desktop menu element (used to do nothing).
  - Cleanup of theme definitions, and improve theme for snapping.
- Run autostart applications as systemd user services.
  - This allows us to view the logs of the user services in journald.
  - It is easier to monitor these services, and restart them.
  - Services include: waybar, swaybg, mako, ghaf-launcher (nwg-drawer), and autolocking.
  - These services properly quit when the user logs out.

## Checklist for things done

- [x] Summary of the proposed changes in the PR description
- [x] More detailed description in the commit message(s)
- [x] Commits are squashed into relevant entities - avoid a lot of minimal dev time commits in the PR
- [x] [Contribution guidelines](https://github.com/tiiuae/ghaf/blob/main/CONTRIBUTING.md) followed
- [ ] Ghaf documentation updated with the commit - https://tiiuae.github.io/ghaf/
- [ ] PR linked to architecture documentation and requirement(s) (ticket id)
- [x] Test procedure described (or includes tests). Select one or more:
  - [x] Tested on Lenovo X1 `x86_64`
  - [ ] Tested on Jetson Orin NX or AGX `aarch64`
  - [ ] Tested on Polarfire `riscv64`
- [ ] Author has run `nix flake check --accept-flake-config` and it passes
- [ ] All automatic Github Action checks pass - see [actions](https://github.com/tiiuae/ghaf/actions)
- [ ] Author has added reviewers and removed PR draft status

## Testing

- By default, you will be logged in automatically.
- You can log out by clicking Log Out in app drawer, which should bring you to the login screen.
- Setting `ghaf.graphics.labwc.autologinUser = null;` would disable autologin, and show the login screen on boot.
- Login, logout multiple times. Should not cause system to go in bad state.
- In login screen, plug and unplug external monitors. Should not glitch or crash.
  - Login prompt is shown on monitor with cursor, moving cursor to other monitor would move the prompt.
  - Other monitors should only show clock on the centre.
- All applications should be launchable after re-logins.
- Boot time shouldn't be significantly affected.
- Fingerprint authentication should work with both lock screen and login screen. Login screen should not hog access to fingerprint reader after login.
  - With same previous caveats with gtklock.
- Test zoom keybindings on desktop, and login screen (it should work there too).
- Run `reuse lint`, should pass with no issues.
- Open/close launcher multiple times using taskbar, should be fast and responsive.
- Open/close launcher using Super Left/Windows key, should be fast.
- The drawer should not impede on the functionality of zoom (since it is using the same modifier key).

### CODE REVIEW

**Review by brianmcgillion — APPROVED** [review]

**Review by vunnyso — APPROVED** [review]

**Comment by milva-unikie** [comment]
I have a few notes :D Overall I think this PR includes amazing improvements and new features. Happy to provide more details if something is unclear in my comment!

For clarity:
- Green Log Out -option = logout/login
- Red Lock -option = lock/unlock

### Tested on Lenovo-X1 (debug)

**Serious issues:**
- Each logout/login increases the CPU usage of Gui-vm about 20 %. After logging out and back in 5 times the usage stays close to 100 %. This is also easy to hear from the fans.
- Login or unlocking with Yubikey does not work. I am using one of the keys in `modules/common/development/authorized_yubikeys.nix`. They should work automatically in all debug builds.

**Smaller issues / usability problems:**
- When fingerprint is enrolled `[ghaf@gui-vm:~]$ fprintd-enroll -f right-index-finger`:
  - There is no option to login with password. After you fail fingerprint 3 times you get 1 chance to use password and if that is wrong you need to start again with fingerprints.
  - Enter can not be used to select `Log in` button when giving the fingerprint. User needs to press tab 2 times to select the correct button or use mouse to click the button.
  - When logging in, you get a prompt `Place your right index finger on the fingerprint reader`. Nothing happens when you place the finger on reader. User must realize to click `Log in` either before or after placing the finger on reader. This is a bit different from the lock where you need to first click `Unlock` or press enter to get the prompt for the fingerprint. After that fingerprint works automatically.
  - After trying to login to non-existing user, fingerprint login is no longer available
    1. Logout and try to login to non-existing account with wrong password => login failed.
    2. Try to login back to Ghaf-account, no option to use fingerprint any more.
    3. Login with password and try to use the lock, no option to use fingerprint any more.
    4. Enrolling the fingerprint again does not work.
 ```
[ghaf@gui-vm:~]$ fprintd-enroll -f right-index-finger
Using device /net/reactivated/Fprint/Device/0
failed to claim device: GDBus.Error:net.reactivated.Fprint.Error.Internal: Open failed with error: Device 06cb:00fc is already open
 ```


- Zoom can not be switched on or off while on lock screen. If it was already on before locking it does work.
- When logging out zoom turns off, but it can be turned back on while in login screen.
- Brightness control works on login screen but not on lock screen.
- Login and lock screens always stay on internal display. Moving mouse to the external monitor did not change that. Also even if you click logout or lock from the external monitor the prompts are still in internal display.
- When giving a password during login there is a `cancel`-button, but it is kind of hard to read with grey font.
- As a bonus issue, I somehow managed to open the app menu once as a separate window. No idea how and was not able to reproduce this. The window was fully functional and could be moved around. Not expecting anything to be done for this. 
IMG_8103


**Working:**
- All the other things mentioned in Testing-section
- External monitors do not cause issues in login/lock screen
- Launcher works well both from taskbar and with Windows-key
- Audio-controls work promptly
- `Reuse lint` passes
- Test-automation passes

Other notes:
- Boot time is a few seconds slower than on mainline. Not a significant change.
- I did not have time to try disabling the `autologin` today, will test that tomorrow.

**Comment by milva-unikie** [comment]
> > Login or unlocking with Yubikey does not work. I am using one of the keys in modules/common/development/authorized_yubikeys.nix. They should work automatically in all debug builds.
> 
> Does this work on mainline? This PR shouldn’t change behaviour of locking at least.

I did not check the mainline from today, but it was working earlier this week. I can check this tomorrow.

**Comment by milva-unikie** [comment]
> > > Login or unlocking with Yubikey does not work. I am using one of the keys in modules/common/development/authorized_yubikeys.nix. They should work automatically in all debug builds.
> > 
> > 
> > Does this work on mainline? This PR shouldn’t change behaviour of locking at least.
> 
> I did not check the mainline from today, but it was working earlier this week. I can check this tomorrow.

You were correct, the Yubikey issue is not caused by this PR. It broke yesterday when https://github.com/tiiuae/ghaf/pull/703 was merged. I created a bug about that. Sorry for the confusion.

**Comment by milva-unikie** [comment]
`autologinUser` works well.

**Comment by milva-unikie** [comment]
**Lenovo-X1** (lenovo-x1-carbon-gen11-debug)
- CPU issue with login/logout has been fixed


**Orin-AGX** (packages.aarch64-linux.nvidia-jetson-orin-agx-debug-flash-script)
- When `Log Out` is clicked, the screen goes black. I tried to login "blindly" but nothing happened. Also tried using the debug-ethernet, connection to host gets lost as soon as you log out.
- Test-automation passes

Orin-NX testing will have to wait until Monday :)

**Comment by milva-unikie** [comment]
> **Orin-AGX** (packages.aarch64-linux.nvidia-jetson-orin-agx-debug-flash-script)
> 
>     * When `Log Out` is clicked, the connection to external monitor is lost. I tried to login "blindly" but nothing happened. Also tried using the debug-ethernet, connection to host gets lost as soon as you log out.
> 
>     * Test-automation passes

Similar issue with Orin-NX (packages.aarch64-linux.nvidia-jetson-orin-nx-debug). With NX it seems to work fine the first time you log out and back in. If you log out a second time, the graphical user interface will disappear.

**Comment by milva-unikie** [comment]
**Lenovo-X1** (.#lenovo-x1-carbon-gen11-debug)

All of the major issues have been fixed. 

**Smaller issues / usability problems:** (The ones that are still valid, no new things added. I don't think these need to be fixed for this pr, this is mostly for future reference :))
- When fingerprint is enrolled `[ghaf@gui-vm:~]$ fprintd-enroll -f right-index-finger`:
     - There is no option to login with password. After you fail fingerprint 3 times you get 1 chance to use password and if that is wrong you need to start again with fingerprints.
     - Enter can not be used to select `Log in` button when giving the fingerprint. User needs to press tab 2 times to select the correct button or use mouse to click the button.
     - When logging in, you get a prompt `Place your right index finger on the fingerprint reader`. Nothing happens when you place the finger on reader. User must realize to click `Log in` either before or after placing the finger on reader. This is a bit different from the lock where you need to first click `Unlock` or press enter to get the prompt for the fingerprint. After that fingerprint works automatically.
- Zoom can not be switched on or off while on lock screen. If it was already on before locking it does work.
- When logging out zoom turns off, but it can be turned back on while in login screen.
- Brightness control works on login screen but not on lock screen.
- Login and lock screens always stay on internal display. Moving mouse to the external monitor did not change that.  Also even if you click logout or lock from the external monitor the prompts are still in internal display.
- When giving a password during login there is a cancel-button, but it is kind of hard to read with grey font.


**Orin-AGX** (packages.aarch64-linux.nvidia-jetson-orin-agx-debug-flash-script)
- Bug: Opening the app menu right after logging in often opens the menu in separate detached window. When app menu is detached Log Out, Firefox and Windows can not be opened.
- Logout/login works now.

**Orin-NX** (packages.aarch64-linux.nvidia-jetson-orin-nx-debug)
- Same bug as in Orin-AGX: Opening the app menu right after logging in often opens the menu in separate detached window. When app menu is detached Log Out, Firefox and Windows can not be opened.
- Logout/login works now.

20240705_18h09m37s_grim
This is the same issue that I noticed before on X1, but with Orins it is easily reproducible.

Bonus finding from this round of testing: I accidentally managed to change the keyboard layout to arabic and was quite confused for a while. Reading the code changes helped to figure out that there was a Alt+Shift shortcut added for changing between english, arabic and finnish. Great addition when you know how it works.

**Comment by milva-unikie** [comment]
Detached app menu bug is fixed with both Orin-AGX and Orin-NX. I think this pr is now good to go in.

**Pull request merged**
