### PR TITLE
Add Hydra Jobs for doc-packages

### PR DESCRIPTION
**Pull request by mikatammi**
Create Hydra Jobs for packages:
* x86_64-linux.doc
* aarch64-linux.doc

Signed-off-by: Mika Tammi <mika.tammi@unikie.com>

### CODE REVIEW

**Review by tervis-unikie — COMMENTED** [review]
Commit message does not explain why this is done, and I don't see a reason to build docs on hydra.

**Comment by mikatammi** [comment]
I was thinking it is so small target it doesn't really matter if we build it on hydra or not. But if it takes hours to build, then something must be wrong somewhere. Most of the packages should be just coming from cache.nixos.org and then the documentation should be simply built

**Review by vilvo — APPROVED** [review]
I don't mind this. 
There's already GHA to build and publish the documentation to https://tiiuae.github.io/ghaf/
If seen useful in nix caches, please go ahead and merge.

**Comment by mikatammi** [comment]
Closing this now as this is aleady quite dated and I have my own hydra setup which does build everything now based on:
https://github.com/mikatammi/ghaf-hydra

**Pull request closed without merging**
