### PR TITLE
Add Ghaf icons

### PR DESCRIPTION
**Pull request by unbel13ver**
The assets directory is moved out from the modules to the source tree since it does not contain Nix source code.

The icons are stored in two formats: .png is used by weston and .svg is stored as a source for possible future conversions.

Imagemagick can not convert .svg to .png since it supports mostly raster graphics format. I made it using Inkscape, but I believe trying to convert svgs on the fly every build will carry huge Inkscape as a buildHost dependency and in future will cause troubles with crosscompilation.

### CODE REVIEW

**Comment by jenninikko** [comment]
Is it possible to have all icons in the same SVG format?

**Comment by unbel13ver** [comment]
> Is it possible to have all icons in the same SVG format?

Weston DE does not support icons in SVG format.

**Review by vilvo — APPROVED** [review]

**Review by jenninikko — APPROVED** [review]

**Comment by vilvo** [comment]
Just for the record - imagemagick convert (svg -> png) via nix packaging would’ve been nice but not essential in the context of coming demo

**Comment by unbel13ver** [comment]
> Just for the record - imagemagick convert (svg -> png) via nix packaging would’ve been nice but not essential in the context of coming demo

I've updated the PR description about this.

**Comment by vilvo** [comment]
> > Just for the record - imagemagick convert (svg -> png) via nix packaging would’ve been nice but not essential in the context of coming demo
> 
> I've updated the PR description about this.

How about `rsvg-convert`?

screencapture

**Review by brianmcgillion — APPROVED** [review]

**Pull request merged**
