### PR TITLE
bump some tools

### PR DESCRIPTION
**Pull request by brianmcgillion**
a partial bump of the available tools updates

includes the latest fixes for the control panel

-------

## Description of changes

Some small changes to microvm and the supporting tools

## Checklist for things done

- [x] Summary of the proposed changes in the PR description
- [x] More detailed description in the commit message(s)
- [x] Commits are squashed into relevant entities - avoid a lot of minimal dev time commits in the PR
- [x] [Contribution guidelines](https://github.com/tiiuae/ghaf/blob/main/CONTRIBUTING.md) followed
- [ ] Ghaf documentation updated with the commit - https://tiiuae.github.io/ghaf/
- [ ] PR linked to architecture documentation and requirement(s) (ticket id)
- [x] Test procedure described (or includes tests). Select one or more:
  - [x] Tested on Lenovo X1 `x86_64`
  - [ ] Tested on Jetson Orin NX or AGX `aarch64`
  - [ ] Tested on Polarfire `riscv64`
- [x] Author has run `make-checks` and it passes
- [x] All automatic Github Action checks pass - see [actions](https://github.com/tiiuae/ghaf/actions)
- [x] Author has added reviewers and removed PR draft status
- [ ] Change requires full re-installation
- [x] Change can be updated with `nixos-rebuild ... switch`

## Instructions for Testing

- [x] List all targets that this applies to:
all targets
- [ ] Is this a new feature
  - [ ] List the test steps to verify:
- [x] If it is an improvement how does it impact existing functionality?
minor version updates
control panel updates - 

Green/OK statuses for all VMs and services
Display settings: resolution and scale can be changed, confirmation popup added
Start and stop apps (only once because of some internal library bug)
Also button for launching audio control widget added, but not tested

### CODE REVIEW

**Review by mbssrc — APPROVED** [review]

**Comment by barnabakos** [comment]
1 commit: 83bacdfe781d421149275e607a0b263152bf18a8
commit is on top of latest tip of Ghaf main: 147f806264d2fb9d9026d4221b7cfbd69587bb61

platform: **Lenovo X1 Carbon; flash script; USB SSD**
- ci-test-automation suite: ok
- starting apps: ok
- regression / ad-hoc testing: ok

#### works:
- statuses are green/OK for VMs and services
- resolution & scale can be changed; there is confirmation popup

#### notes:
- Control panel doesn't remember the applied resolution & scale settings after it was closed
  opening again shows the deafult values
- setting the scale other than 100% will zoom in the top centre of the screen
  anything that doesn't fit that area will be unreachable: app menu; widgets; parts of running apps
- resolution & scale settings are restored to default after logout / reboot / shutdown
- taskbar doesn't get stretched to screen width when selecting a higher resolution
- start / stop apps doesn't seem to work
- button for launching audio control widget doesn't work

#### issues:
- N/A

**Comment by johannarautanen** [comment]
Tested on native Orin-AGX (flashed to the memory card) (commit: 83bacdfe781d421149275e607a0b263152bf18a8)

Working:
- no new findings 
- all other ghaf apps can be launched and close
- ci-test automation cases ok

**Comment by leivos-unikie** [comment]
Tested on Orin-NX (native build)
- ci-test-automation passes except all tests requiring ssh connection to net-vm fail
- tried ssh to net-vm also manually, it does not work (ping works)
- also eth passthough to net-vm does not work (ping works)

Other known issues (also in mainline)
- taskbar not available

**Comment by milva-unikie** [comment]
Tested on Lenovo-X1 (`nixos-rebuild switch`)

High cpu usage of Control Panel has been fixed.

**Comment by dmitry-erin** [comment]
> 1 commit: [83bacdf](https://github.com/tiiuae/ghaf/commit/83bacdfe781d421149275e607a0b263152bf18a8) commit is on top of latest tip of Ghaf main: [147f806](https://github.com/tiiuae/ghaf/commit/147f806264d2fb9d9026d4221b7cfbd69587bb61)
> 
> platform: **Lenovo X1 Carbon; flash script; USB SSD**
> 
> * ci-test-automation suite: ok
> * starting apps: ok
> * regression / ad-hoc testing: ok
> 
> #### works:
> * statuses are green/OK for VMs and services
> * resolution & scale can be changed; there is confirmation popup
> 
> #### notes:
> * Control panel doesn't remember the applied resolution & scale settings after it was closed
>   opening again shows the deafult values
> * setting the scale other than 100% will zoom in the top centre of the screen
>   anything that doesn't fit that area will be unreachable: app menu; widgets; parts of running apps
> * resolution & scale settings are restored to default after logout / reboot / shutdown
> * taskbar doesn't get stretched to screen width when selecting a higher resolution
> * start / stop apps doesn't seem to work
> * button for launching audio control widget doesn't work
> 
> #### issues:
> * N/A

1. The display settings are under development, the task is not completed, so there are a lot of things to do (read current mode, all supported modes, adjusting the control panel's window to fit the scaled screen and etc)
2. Restoring defaults after logout/rebooting/shutdwon is not control's panel issue, should be fixed in OS settings or somewhere else.
3. Start&stop issue is known, responsible people are looking for a solution
4. The advanced audio settings button sends the dbus message, which must be handled by audio widget.  The receiving part is not ready yet as far as I know.

**Pull request merged**
